*** Starting uWSGI 2.0.19.1 (64bit) on [Thu Dec  1 05:35:35 2022] ***
compiled with version: 10.2.1 20210110 on 01 December 2022 05:17:15
os: Linux-5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022
nodename: d49d4cee3b19
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 32
current working directory: /app
writing pidfile to /tmp/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:9090 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.15 (default, Nov 15 2022, 22:06:14)  [GCC 10.2.1 20210110]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x562beafbab70
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "/app/./_wsgi.py", line 32, in <module>
    from polygonSegmentation import SegmentationModel
  File "/app/./polygonSegmentation.py", line 7, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 9)
spawned uWSGI worker 1 (pid: 44, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 44|app: -1|req: -1/1] 172.24.0.1 () {32 vars in 646 bytes} [Thu Dec  1 05:38:16 2022] GET /health => generated 21 bytes in 1 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
*** Starting uWSGI 2.0.19.1 (64bit) on [Thu Dec  1 11:59:05 2022] ***
compiled with version: 10.2.1 20210110 on 01 December 2022 05:17:15
os: Linux-5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022
nodename: 558cc8d0493d
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 32
current working directory: /app
writing pidfile to /tmp/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:9090 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.15 (default, Nov 15 2022, 22:06:14)  [GCC 10.2.1 20210110]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x563a0e252b70
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "/app/./_wsgi.py", line 32, in <module>
    from polygonSegmentation import SegmentationModel
  File "/app/./polygonSegmentation.py", line 8, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 9)
spawned uWSGI worker 1 (pid: 44, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 44|app: -1|req: -1/1] 172.26.0.1 () {34 vars in 660 bytes} [Thu Dec  1 12:03:13 2022] GET / => generated 21 bytes in 1 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 44|app: -1|req: -1/2] 172.26.0.1 () {34 vars in 660 bytes} [Thu Dec  1 12:03:16 2022] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
...brutally killing workers...
*** Starting uWSGI 2.0.19.1 (64bit) on [Tue Dec 13 07:37:08 2022] ***
compiled with version: 10.2.1 20210110 on 13 December 2022 06:58:51
os: Linux-5.4.0-107-generic #121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022
nodename: f6e8a45410fa
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 48
current working directory: /app
writing pidfile to /tmp/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:9090 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.16 (default, Dec  8 2022, 03:18:29)  [GCC 10.2.1 20210110]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x564730cedb80
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "/app/./_wsgi.py", line 32, in <module>
    from polygonSegmentation import SegmentationModel
  File "/app/./polygonSegmentation.py", line 8, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 9)
spawned uWSGI worker 1 (pid: 60, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 60|app: -1|req: -1/1] 103.160.78.156 () {32 vars in 659 bytes} [Tue Dec 13 07:38:07 2022] GET /health => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 60|app: -1|req: -1/2] 171.246.241.142 () {32 vars in 638 bytes} [Tue Dec 13 07:38:11 2022] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 60|app: -1|req: -1/3] 171.246.241.142 () {32 vars in 593 bytes} [Tue Dec 13 07:38:13 2022] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
...brutally killing workers...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /app
closing all non-uwsgi socket fds > 2 (max_fd = 1048576)...
found fd 3 mapped to socket 0 (0.0.0.0:9090)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from /etc/uwsgi/uwsgi.ini
*** Starting uWSGI 2.0.19.1 (64bit) on [Tue Dec 13 07:42:51 2022] ***
compiled with version: 10.2.1 20210110 on 13 December 2022 06:58:51
os: Linux-5.4.0-107-generic #121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022
nodename: f6e8a45410fa
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 48
current working directory: /app
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 0.0.0.0:9090 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.16 (default, Dec  8 2022, 03:18:29)  [GCC 10.2.1 20210110]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x558d05acc5a0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "/app/./_wsgi.py", line 32, in <module>
    from polygonSegmentation import SegmentationModel
  File "/app/./polygonSegmentation.py", line 8, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 9)
spawned uWSGI worker 1 (pid: 109, cores: 1)
*** Starting uWSGI 2.0.19.1 (64bit) on [Tue Dec 13 07:44:07 2022] ***
compiled with version: 10.2.1 20210110 on 13 December 2022 06:58:51
os: Linux-5.4.0-107-generic #121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022
nodename: f6e8a45410fa
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 48
current working directory: /app
writing pidfile to /tmp/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:9090 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.16 (default, Dec  8 2022, 03:18:29)  [GCC 10.2.1 20210110]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55a8a62bab80
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "/app/./_wsgi.py", line 32, in <module>
    from polygonSegmentation import SegmentationModel
  File "/app/./polygonSegmentation.py", line 8, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 9)
spawned uWSGI worker 1 (pid: 60, cores: 1)
...brutally killing workers...
*** Starting uWSGI 2.0.19.1 (64bit) on [Tue Dec 13 07:45:32 2022] ***
compiled with version: 10.2.1 20210110 on 13 December 2022 06:58:51
os: Linux-5.4.0-107-generic #121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022
nodename: f6e8a45410fa
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 48
current working directory: /app
writing pidfile to /tmp/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:9090 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.16 (default, Dec  8 2022, 03:18:29)  [GCC 10.2.1 20210110]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x5592a0b26b80
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "/app/./_wsgi.py", line 32, in <module>
    from polygonSegmentation import SegmentationModel
  File "/app/./polygonSegmentation.py", line 8, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 9)
spawned uWSGI worker 1 (pid: 60, cores: 1)
...brutally killing workers...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /app
closing all non-uwsgi socket fds > 2 (max_fd = 1048576)...
found fd 3 mapped to socket 0 (0.0.0.0:9090)
*** Starting uWSGI 2.0.19.1 (64bit) on [Tue Dec 13 07:48:23 2022] ***
compiled with version: 10.2.1 20210110 on 13 December 2022 06:58:51
os: Linux-5.4.0-107-generic #121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022
nodename: f6e8a45410fa
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 48
current working directory: /app
writing pidfile to /tmp/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:9090 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.16 (default, Dec  8 2022, 03:18:29)  [GCC 10.2.1 20210110]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x559e13b60b80
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "/app/./_wsgi.py", line 32, in <module>
    from polygonSegmentation import SegmentationModel
  File "/app/./polygonSegmentation.py", line 8, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 9)
spawned uWSGI worker 1 (pid: 60, cores: 1)
*** Starting uWSGI 2.0.19.1 (64bit) on [Tue Dec 13 07:59:04 2022] ***
compiled with version: 10.2.1 20210110 on 13 December 2022 06:58:51
os: Linux-5.4.0-107-generic #121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022
nodename: fe4928e392cc
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 48
current working directory: /app
writing pidfile to /tmp/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:9090 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.16 (default, Dec  8 2022, 03:18:29)  [GCC 10.2.1 20210110]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55eba356eb80
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "/app/./_wsgi.py", line 32, in <module>
    from polygonSegmentation import SegmentationModel
  File "/app/./polygonSegmentation.py", line 8, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 9)
spawned uWSGI worker 1 (pid: 61, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 61|app: -1|req: -1/1] 171.246.241.142 () {34 vars in 669 bytes} [Tue Dec 13 07:59:24 2022] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 61|app: -1|req: -1/2] 171.246.241.142 () {32 vars in 593 bytes} [Tue Dec 13 07:59:24 2022] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 61|app: -1|req: -1/3] 171.246.241.142 () {34 vars in 669 bytes} [Tue Dec 13 07:59:31 2022] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 61|app: -1|req: -1/4] 171.246.241.142 () {32 vars in 593 bytes} [Tue Dec 13 07:59:31 2022] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
*** Starting uWSGI 2.0.19.1 (64bit) on [Tue Dec 13 08:01:12 2022] ***
compiled with version: 10.2.1 20210110 on 13 December 2022 06:58:51
os: Linux-5.4.0-107-generic #121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022
nodename: fe4928e392cc
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 48
current working directory: /app
writing pidfile to /tmp/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:9090 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.16 (default, Dec  8 2022, 03:18:29)  [GCC 10.2.1 20210110]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55c95bad5b80
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "/app/./_wsgi.py", line 32, in <module>
    from polygonSegmentation import SegmentationModel
  File "/app/./polygonSegmentation.py", line 8, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 9)
spawned uWSGI worker 1 (pid: 61, cores: 1)
*** Starting uWSGI 2.0.19.1 (64bit) on [Tue Dec 13 08:01:49 2022] ***
compiled with version: 10.2.1 20210110 on 13 December 2022 06:58:51
os: Linux-5.4.0-107-generic #121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022
nodename: 7a230665d241
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 48
current working directory: /app
writing pidfile to /tmp/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:9090 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.16 (default, Dec  8 2022, 03:18:29)  [GCC 10.2.1 20210110]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55953d38eb80
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "/app/./_wsgi.py", line 32, in <module>
    from polygonSegmentation import SegmentationModel
  File "/app/./polygonSegmentation.py", line 8, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 9)
spawned uWSGI worker 1 (pid: 61, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 61|app: -1|req: -1/1] 171.246.241.142 () {34 vars in 669 bytes} [Tue Dec 13 08:02:04 2022] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 61|app: -1|req: -1/2] 171.246.241.142 () {32 vars in 593 bytes} [Tue Dec 13 08:02:04 2022] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 61|app: -1|req: -1/3] 171.246.241.142 () {34 vars in 669 bytes} [Tue Dec 13 08:02:06 2022] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 61|app: -1|req: -1/4] 171.246.241.142 () {32 vars in 593 bytes} [Tue Dec 13 08:02:06 2022] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
*** Starting uWSGI 2.0.19.1 (64bit) on [Tue Dec 13 10:06:31 2022] ***
compiled with version: 10.2.1 20210110 on 13 December 2022 08:28:30
os: Linux-5.4.0-107-generic #121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022
nodename: 9c7ac204b6f5
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 48
current working directory: /app
writing pidfile to /tmp/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:9090 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.16 (default, Dec  8 2022, 03:18:29)  [GCC 10.2.1 20210110]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55d37a7c4b80
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "/app/./_wsgi.py", line 32, in <module>
    from polygonSegmentation import SegmentationModel
  File "/app/./polygonSegmentation.py", line 8, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 9)
spawned uWSGI worker 1 (pid: 61, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 61|app: -1|req: -1/1] 171.246.241.142 () {32 vars in 638 bytes} [Tue Dec 13 10:19:33 2022] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 61|app: -1|req: -1/2] 171.246.241.142 () {32 vars in 593 bytes} [Tue Dec 13 10:19:33 2022] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 61|app: -1|req: -1/3] 171.246.241.142 () {34 vars in 669 bytes} [Tue Dec 13 10:19:36 2022] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 61|app: -1|req: -1/4] 171.246.241.142 () {32 vars in 593 bytes} [Tue Dec 13 10:19:37 2022] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 61|app: -1|req: -1/5] 171.246.241.142 () {34 vars in 669 bytes} [Tue Dec 13 10:19:45 2022] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 61|app: -1|req: -1/6] 171.246.241.142 () {32 vars in 593 bytes} [Tue Dec 13 10:19:45 2022] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
*** Starting uWSGI 2.0.19.1 (64bit) on [Tue Dec 13 11:25:38 2022] ***
compiled with version: 10.2.1 20210110 on 13 December 2022 08:28:30
os: Linux-5.4.0-107-generic #121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022
nodename: 3a16843d65ad
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 48
current working directory: /app
writing pidfile to /tmp/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:9090 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.16 (default, Dec  8 2022, 03:18:29)  [GCC 10.2.1 20210110]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x562114fd6b80
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "/app/./_wsgi.py", line 32, in <module>
    from polygonSegmentation import SegmentationModel
  File "/app/./polygonSegmentation.py", line 8, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 9)
spawned uWSGI worker 1 (pid: 61, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 61|app: -1|req: -1/1] 103.160.78.156 () {32 vars in 659 bytes} [Tue Dec 13 11:26:15 2022] GET /health => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 61|app: -1|req: -1/2] 171.246.241.142 () {34 vars in 669 bytes} [Tue Dec 13 11:26:18 2022] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 61|app: -1|req: -1/3] 171.246.241.142 () {32 vars in 593 bytes} [Tue Dec 13 11:26:19 2022] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 61|app: -1|req: -1/4] 171.246.241.142 () {32 vars in 557 bytes} [Tue Dec 13 12:17:29 2022] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 61|app: -1|req: -1/5] 171.246.241.142 () {32 vars in 523 bytes} [Tue Dec 13 12:17:31 2022] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
...brutally killing workers...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /app
closing all non-uwsgi socket fds > 2 (max_fd = 1048576)...
found fd 3 mapped to socket 0 (0.0.0.0:9090)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from /etc/uwsgi/uwsgi.ini
*** Starting uWSGI 2.0.19.1 (64bit) on [Tue Dec 13 12:24:01 2022] ***
compiled with version: 10.2.1 20210110 on 13 December 2022 08:28:30
os: Linux-5.4.0-107-generic #121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022
nodename: 3a16843d65ad
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 48
current working directory: /app
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 0.0.0.0:9090 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.16 (default, Dec  8 2022, 03:18:29)  [GCC 10.2.1 20210110]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x56298c8af5a0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "/app/./_wsgi.py", line 32, in <module>
    from polygonSegmentation import SegmentationModel
  File "/app/./polygonSegmentation.py", line 8, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 9)
spawned uWSGI worker 1 (pid: 114, cores: 1)
*** Starting uWSGI 2.0.19.1 (64bit) on [Tue Dec 13 15:30:21 2022] ***
compiled with version: 10.2.1 20210110 on 13 December 2022 13:07:47
os: Linux-5.4.0-107-generic #121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022
nodename: 00f490757817
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 48
current working directory: /app
writing pidfile to /tmp/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:9090 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.16 (default, Dec  8 2022, 03:18:29)  [GCC 10.2.1 20210110]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x563451fe6b80
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "/app/./_wsgi.py", line 32, in <module>
    from polygonSegmentation import SegmentationModel
  File "/app/./polygonSegmentation.py", line 8, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 9)
spawned uWSGI worker 1 (pid: 60, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 60|app: -1|req: -1/1] 171.246.241.142 () {32 vars in 557 bytes} [Tue Dec 13 15:30:32 2022] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
*** Starting uWSGI 2.0.19.1 (64bit) on [Tue Dec 13 15:34:41 2022] ***
compiled with version: 10.2.1 20210110 on 13 December 2022 13:07:47
os: Linux-5.4.0-107-generic #121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022
nodename: 00f490757817
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 48
current working directory: /app
writing pidfile to /tmp/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:9090 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.16 (default, Dec  8 2022, 03:18:29)  [GCC 10.2.1 20210110]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x5603bbcdeb80
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "/app/./_wsgi.py", line 32, in <module>
    from polygonSegmentation import SegmentationModel
  File "/app/./polygonSegmentation.py", line 8, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 9)
spawned uWSGI worker 1 (pid: 60, cores: 1)
*** Starting uWSGI 2.0.19.1 (64bit) on [Thu Dec 22 17:23:52 2022] ***
compiled with version: 10.2.1 20210110 on 22 December 2022 17:12:17
os: Linux-5.4.0-107-generic #121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022
nodename: 14b1257cc8e0
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 48
current working directory: /app
writing pidfile to /tmp/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:9090 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.16 (default, Dec 21 2022, 19:32:01)  [GCC 10.2.1 20210110]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55ce4838bb80
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "/app/./_wsgi.py", line 32, in <module>
    from polygonSegmentation import SegmentationModel
  File "/app/./polygonSegmentation.py", line 8, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 9)
spawned uWSGI worker 1 (pid: 60, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 60|app: -1|req: -1/1] 103.160.78.156 () {32 vars in 667 bytes} [Thu Dec 22 17:25:50 2022] GET /health => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 60|app: -1|req: -1/2] 103.160.78.156 () {32 vars in 671 bytes} [Thu Dec 22 17:28:36 2022] GET /health => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 60|app: -1|req: -1/3] 103.160.78.156 () {32 vars in 659 bytes} [Thu Dec 22 17:28:41 2022] GET /health => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 60|app: -1|req: -1/4] 103.160.78.156 () {32 vars in 659 bytes} [Thu Dec 22 17:28:41 2022] GET /health => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 60|app: -1|req: -1/5] 103.160.78.156 () {32 vars in 659 bytes} [Thu Dec 22 17:28:41 2022] GET /health => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 60|app: -1|req: -1/6] 103.160.78.156 () {32 vars in 659 bytes} [Thu Dec 22 17:28:41 2022] GET /health => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 60|app: -1|req: -1/7] 103.160.78.156 () {32 vars in 659 bytes} [Thu Dec 22 17:28:41 2022] GET /health => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 60|app: -1|req: -1/8] 103.160.78.156 () {32 vars in 659 bytes} [Thu Dec 22 17:28:46 2022] GET /health => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 60|app: -1|req: -1/9] 171.246.203.154 () {32 vars in 557 bytes} [Thu Dec 22 17:28:54 2022] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 60|app: -1|req: -1/10] 171.246.203.154 () {32 vars in 523 bytes} [Thu Dec 22 17:28:56 2022] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
